#!/usr/bin/env python3
"""
TripleWrapper GUI - Entry point script
"""

import sys
import os

# Add the package to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'triplewrapper_gui'))

from triplewrapper_gui.main import main

if __name__ == '__main__':
    sys.exit(main())